[package]
name = "ordinal"
version = "0.2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Formatting of ordinals (1st, 2nd, 3rd etc)"
repository = "https://github.com/dtolnay/ordinal"
documentation = "https://github.com/dtolnay/ordinal"

[dependencies]
num-integer = "0.1"

[dev-dependencies]
num-bigint = "0.2"
num-traits = "0.2"

[badges]
travis-ci = { repository = "dtolnay/ordinal" }
